### ISSUE TITLE
文档中的字符被翻译了，希望能改进。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [k1995/github-i18n-plugin#13]
https://github.com/IrineSistiana/mosdns/wiki/Configuration
type ，都被翻译成 请键入了
<img width="822" alt="chrome_截图_sd01xScGAqlsCVRf" src="https://user-images.githubusercontent.com/10376283/114286282-ee10a080-9a8f-11eb-858e-2c58ecb75ec5.png">

**Comment by maboloshi** [comment]
此问题在 312564a 中貌似已修复 请更新脚本到最新版本

**Comment by wy16W2pIilK1xgqN** [comment]
> 此问题在 [312564a](https://github.com/k1995/github-i18n-plugin/commit/312564a52d8ff41e3e8d6f743c4a4a63ca51fc17) 中貌似已修复 请更新脚本到最新版本

版本号是：  0.11
应该是最新了，还有更高的版本吗？

**Comment by maboloshi** [comment]
嗯 0.11 现在是最新的 我刷新一下 也有这个问题 :disappointed_relieved:

**Comment by k1995** [comment]
ad970d39234ef3c99aa4f0bb696e7e9fe21d2cf2 已解决，请升级到0.12版本

**Comment by wy16W2pIilK1xgqN** [comment]
> [ad970d3](https://github.com/k1995/github-i18n-plugin/commit/ad970d39234ef3c99aa4f0bb696e7e9fe21d2cf2) 已解决，请升级到0.12版本
测试，有效。
谢谢你帮助。😋
