### ISSUE TITLE
“正在关注”可以更改成“关注”

### ISSUE THREAD

**Issue by shaoxiongdu** [k1995/github-i18n-plugin#16]
User & Organization 中 “正在关注”可以更改成“关注”  更加符合国人的习惯

![项目部分](https://user-images.githubusercontent.com/73691342/116225683-b76fa100-a784-11eb-9841-2f96e8f31fb4.png)

![示例部分](https://user-images.githubusercontent.com/73691342/116225744-c6eeea00-a784-11eb-8c35-556c300044ec.png)

**Comment by k1995** [comment]
#11
