### ISSUE TITLE
navigator.languages

### ISSUE THREAD

**Issue by gcqmkm02** [k1995/github-i18n-plugin#3]
你好。脚本不看navigator.languages的。
我想有的如果navigator.languages.includes("zh") 的话作lang="zh-CN"代码。
谢谢

**Comment by k1995** [comment]
现在策略是“zh”开头的，都会作为“zh-CN”来处理。
也就是说“中文”，包括“繁体”，都会显示为“简体中文”，你是想达到什么目的？

**Comment by gcqmkm02** [comment]
我的navigator.languages是["tr", "fr", "zh"]
如果这样的话苯教不翻译文章。都是英文的。

**Comment by gcqmkm02** [comment]
我自己变化了。很容易的。只有更新的时候需要在边代码的。 
const langs = navigator.languages;
if(langs.includes("zh")) {
        lang = "zh-CN";

    }
