### ISSUE TITLE
/.github/workflows/的workflows会被自动翻译成"工作流程"

### ISSUE THREAD

**Issue by JianJia2018** [k1995/github-i18n-plugin#34]
![image](https://user-images.githubusercontent.com/39438074/134790503-07302252-a7ac-451b-9fcd-340d3194a5dc.png)
直接在网页上修改会被提交,导致 github action 失效. 希望加入白名单

**Comment by maboloshi** [comment]
#28 和 #33 就是用来修复这个的

**Comment by JianJia2018** [comment]
> #28 和 #33 就是用来修复这个的

可以了, 但是tampermonkey没更新

**Comment by maboloshi** [comment]
你先尝试一段时间 可能规则还有误伤的可能
