### ISSUE TITLE
貌似无法正常运行

### ISSUE THREAD

**Issue by Red-Spotec** [k1995/github-i18n-plugin#35]
Chrome/94.0.4606.61

下列所有github插件都禁用的情况下
  - Doorcat for GitHub v0.0.15
  - GitHub加速 v1.3.2 
  - Octotree - GitHub code tree v7.1.2 

观察到我控制台的错误(如图)：

![image](https://user-images.githubusercontent.com/90175459/136646973-14a3f44b-6b6c-4384-9c76-e7ecfd7318a7.png)

**Comment by k1995** [comment]
可以了吗
