### ISSUE TITLE
引用的2个资源不存在导致翻译失效

### ISSUE THREAD

**Issue by owedocker** [k1995/github-i18n-plugin#45]
更换如下：
// @require             https://cdnjs.cloudflare.com/ajax/libs/timeago.js/4.0.2/timeago.full.min.js
// @require             https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js

**Comment by k1995** [comment]
存在的啊，你是不是网络问题访问不了。开了代理？

**Comment by k1995** [comment]
c2f9147 已更换为 http://staticfile.org/
