### ISSUE TITLE
cdn.bootcss.com 不稳定

### ISSUE THREAD

**Issue by jiesou** [k1995/github-i18n-plugin#48]
无法翻译，检查发现是无法连接上 cdn.bootcss.com 并且**不是我的网络问题**
![image](https://user-images.githubusercontent.com/84175239/151693572-fdca3a87-e085-478e-b6e9-2dbb5a33e0d5.png)
![image](https://user-images.githubusercontent.com/84175239/151693532-8d16b6af-12a0-4076-a8aa-538aff551ca2.png) 
![image](https://user-images.githubusercontent.com/84175239/151693539-cb461ebe-7e90-468f-9de5-99ce40eb8b80.png)
我自己更改 CDN 后一切正常

**Comment by jiesou** [comment]
发现已经有一样的 pr（#46），就把我的关了

**Comment by k1995** [comment]
c2f9147 已更换为 http://staticfile.org/
