### ISSUE TITLE
使用本脚本将导致我在访问他人的库页面时直接卡死

### ISSUE THREAD

**Issue by yuijker** [k1995/github-i18n-plugin#50]
系统：windows 10
浏览器版本：edge 97.0.1072.76
油猴版本：4.13.6138
本脚本版本：0.21
具体情况：
当我不使用本脚本时一切很正常。

![屏幕截图 2022-01-31 152437](https://user-images.githubusercontent.com/72558803/151754532-1a1bf751-629e-4703-802b-e21019466038.png)

但是当我开启脚本时

![屏幕截图 2022-01-31 152558](https://user-images.githubusercontent.com/72558803/151754582-97ce8c9e-b8fb-4132-90a4-7e987334d78e.png)

看起来没什么事，但是我已经无法点击任何链接了，整个页面已经卡死了，CPU利用率也从0.8%暴涨到39.1%。

![屏幕截图 2022-01-31 152637](https://user-images.githubusercontent.com/72558803/151754819-0cc56828-1bae-46fe-bb8b-29d529997a73.png)

![屏幕截图 2022-01-31 153618](https://user-images.githubusercontent.com/72558803/151755178-e5a8cd73-7f71-43ab-aaa0-0bcd9167dbb6.png)

![屏幕截图 2022-01-31 153659](https://user-images.githubusercontent.com/72558803/151755190-9c80e51e-72d2-424f-b5bc-bf0cc5b2b9fc.png)

**Comment by Sabiary** [comment]
今天更新后一样
windows 11
浏览器版本：EDGE 97.0.1072.76
暴力猴版本：2.13.0
本脚本版本：0.21

**Comment by Goojoe** [comment]
系统：windows 10 21H2
浏览器版本：edge 97.0.1072.76
油猴版本：4.13.6138
本脚本版本：0.21
具体情况:
俺也一样
![](https://img.goojoe.cc/2022/02/01/EUu0mOOo.webp)
![](https://img.goojoe.cc/2022/02/01/ua3tn9RB.webp)
我还以为Github崩了,一直卡在主页,CPU暴涨,0.22修复了才能过来评论

**Comment by CN-ycx** [comment]
系统：Windows 8.1
浏览器版本：Chrome 97.0.4692.99
油猴版本：4.13.6138
本脚本版本：0.21
具体情况：
同上
![K4YV`(X7(7(M0G3FL}Y{}S9](https://user-images.githubusercontent.com/6481655/151958238-322c71c8-2fab-455f-af2d-73f1b4f78df2.png)，任务管理器中Github有一个Socket Worket脚本把浏览器进程卡死。
