### ISSUE TITLE
有没有教程，怎么往这个json文件里添加翻译？

### ISSUE THREAD

**Issue by tuwulin365** [k1995/github-i18n-plugin#60]

**Comment by k1995** [comment]
很简单，键名就是你要翻译的英文（需要小写），值就是对应的中文

**Comment by tuwulin365** [comment]
> 很简单，键名就是你要翻译的英文（需要小写），值就是对应的中文
那本地修改完怎么验证？

**Comment by tuwulin365** [comment]
我改了文件路径，但是完全没效果，都是英文。是不是不能使用本地文件？文件路径在浏览器能正常打开。
