### ISSUE TITLE
本插件会错误的翻译代码文件，造成代码损坏

### ISSUE THREAD

**Issue by liyuhaolol** [k1995/github-i18n-plugin#70]
我认为是个BUG，我这边由于一些微小的改动，并不想在本地项目里修改上传。所以直接在github上，点进代码文件，点击“编辑本文件”，就是那个笔，直接在网页上编辑了一下头文件就保存了，结果代码不运行了，仔细一看才发现，我代码里大量的东西都被强制翻译为了中文，甚为无语。。。所以这是个BUG吧？编辑器里的内容，翻译插件应该无视才对吧？

**Comment by k1995** [comment]
39a9366
