### ISSUE TITLE
应该忽略编辑区域

### ISSUE THREAD

**Issue by itodouble** [k1995/github-i18n-plugin#71]
![image](https://github.com/k1995/github-i18n-plugin/assets/13508120/ccd03981-fb7e-438a-890c-e122bbc687f1)
会直接把done换成‘已完成’

**Comment by k1995** [comment]
66f04639b7553af5dc9f4497fa5f8588d8f25590 已解决

**Comment by k1995** [comment]
39a9366 已解决
