### ISSUE TITLE
发现新的翻译错误，以及缺失翻译的问题

### ISSUE THREAD

**Issue by liyuhaolol** [k1995/github-i18n-plugin#73]
![QQ截图20230914220512](https://github.com/k1995/github-i18n-plugin/assets/16422963/467ae2e2-c7e1-4ce0-b02b-b02920e36745)
- L大的个人页面明显可以看到，本插件把Packages翻译成了包，自己的项目名称不应该被翻译才对吧？
![QQ截图20230914220824](https://github.com/k1995/github-i18n-plugin/assets/16422963/7db70f12-7004-43e0-87e4-61191ec5c9d2)
![QQ截图20230914221021](https://github.com/k1995/github-i18n-plugin/assets/16422963/2cfd76dd-6937-4f94-9a71-06a849651b8f)
- 上面两个图，都是未登录，去登录时，是新的界面，本插件完全没有翻译
- 另外“双因素身份验证”听起来也太机翻了吧？难道不应该是“两步验证”么。。。。

**Comment by k1995** [comment]
30115039b793153898d857cda2702b18fd53202e 已解决
