### ISSUE TITLE
近些天的脚本翻译了部分代码

### ISSUE THREAD

**Issue by huangsijun17** [k1995/github-i18n-plugin#77]
近些天在使用时，发现汉化脚本存在过度翻译的情况，部分的代码也被翻译了。
例如：https://github.com/alvistack/ansible-role-sqlite/blob/master/molecule/default/converge.yml
![image](https://github.com/k1995/github-i18n-plugin/assets/31504595/c36acb04-8172-4434-82f7-fe3970a541a0)

**Comment by k1995** [comment]
已修复 ba646119ea93ce3e154530d2eb0d07344dc56466
